"use server";

import { redirect } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import {
  generateTotpSecret,
  encryptSecret,
  decryptSecret,
  buildTotpUri,
  generateTotpQrDataUrl,
  generateRecoveryCodes,
  verifyTotpCode,
} from "@/lib/totp";
import { issueAdminElevatedSession } from "@/lib/admin-auth";

/**
 * Initiates MFA enrollment for the authenticated PLATFORM_ADMIN.
 * Generates an encrypted secret and single-use recovery codes,
 * saving them in public.admin_mfa in a pending (mfa_enabled = false) state.
 */
export async function getOrStartMfaSetupAction(): Promise<{
  secretBase32: string;
  qrCodeUrl: string;
  recoveryCodes: string[];
  alreadyEnabled?: boolean;
} | { error: string }> {
  const supabase = await createServerSupabaseClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/login?next=/admin/setup-2fa");
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("platform_role, full_name")
    .eq("id", user.id)
    .single();

  if (profile?.platform_role !== "PLATFORM_ADMIN") {
    redirect("/403");
  }

  const admin = createAdminClient();

  // Check existing MFA record
  const { data: existingMfa } = await admin
    .from("admin_mfa")
    .select("mfa_enabled, encrypted_secret, secret_iv, secret_tag")
    .eq("user_id", user.id)
    .maybeSingle();

  if (existingMfa?.mfa_enabled) {
    return { alreadyEnabled: true, error: "MFA is already configured for your account." };
  }

  // Generate fresh TOTP secret & recovery codes
  const secretBase32 = generateTotpSecret();
  const { ciphertext, iv, tag } = encryptSecret(secretBase32);
  const { plaintextCodes, hashedCodes } = generateRecoveryCodes(10);

  const { error: upsertError } = await admin.from("admin_mfa").upsert({
    user_id: user.id,
    encrypted_secret: ciphertext,
    secret_iv: iv,
    secret_tag: tag,
    recovery_codes: hashedCodes,
    mfa_enabled: false,
    last_used_counter: 0,
    updated_at: new Date().toISOString(),
  });

  if (upsertError) {
    console.error("Failed storing pending MFA setup:", upsertError);
    return { error: "Could not initiate MFA setup. Please try again." };
  }

  const label = user.email || "Platform Admin";
  const totpUri = buildTotpUri(label, secretBase32, "Sweetly");
  const qrCodeUrl = await generateTotpQrDataUrl(totpUri);

  return {
    secretBase32,
    qrCodeUrl,
    recoveryCodes: plaintextCodes,
  };
}

/**
 * Confirms MFA enrollment by verifying the first TOTP code generated by the admin's app.
 * Only after verification succeeds is mfa_enabled set to true.
 */
export async function confirmMfaEnrollmentAction(code: string): Promise<{ error?: string }> {
  const supabase = await createServerSupabaseClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/login?next=/admin/setup-2fa");
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("platform_role")
    .eq("id", user.id)
    .single();

  if (profile?.platform_role !== "PLATFORM_ADMIN") {
    redirect("/403");
  }

  const admin = createAdminClient();
  const { data: mfaRecord } = await admin
    .from("admin_mfa")
    .select("encrypted_secret, secret_iv, secret_tag, mfa_enabled, last_used_counter")
    .eq("user_id", user.id)
    .single();

  if (!mfaRecord) {
    return { error: "MFA setup session expired. Please refresh the page to restart setup." };
  }

  let secretBase32 = "";
  try {
    secretBase32 = decryptSecret(
      mfaRecord.encrypted_secret,
      mfaRecord.secret_iv,
      mfaRecord.secret_tag
    );
  } catch (err) {
    console.error("Failed decrypting pending MFA secret:", err);
    return { error: "Encryption error. Please regenerate setup." };
  }

  const verification = verifyTotpCode(secretBase32, code, 0, 1);
  if (!verification.valid || verification.matchedCounter === undefined) {
    return { error: "Invalid authenticator code. Please check your app and try again." };
  }

  // Atomically activate MFA
  const { error: updateError } = await admin
    .from("admin_mfa")
    .update({
      mfa_enabled: true,
      last_used_counter: verification.matchedCounter,
      last_verified_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })
    .eq("user_id", user.id);

  if (updateError) {
    console.error("Failed activating MFA:", updateError);
    return { error: "Failed to activate MFA. Please try again." };
  }

  // Establish elevated session
  await issueAdminElevatedSession(user.id);
  redirect("/admin");
}
